apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: core-apps
spec:
  project: default
  source:
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: HEAD
    path: core/apps
    helm:
      valueFiles:
        - ../../clusters/docker-desktop/core/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
