apiVersion: v2
name: cert-manager
description: cert-manager
type: application
version: "1.0.0"
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: "1.10.0"
    repository: https://charts.jetstack.io
