apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:nlykkei/k8sdevops.git
    targetRevision: HEAD
    path: linkerd
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
