apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:nlykkei/k8sdevops.git
    targetRevision: HEAD
    path: linkerd
    helm:
      fileParameters:
        - name: identityTrustAnchorsPEM
          path: certs/ca.crt
        - name: identity.issuer.tls.crtPEM
          path: certs/issuer.crt
        - name: identity.issuer.tls.keyPEM
          path: certs/issuer.key
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
