apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  labels:
    name: apps
spec:
  project: default
  source:
    repoURL: "git@github.com:nlykkei/k8sdevops.git"
    path: clusters/docker-desktop/apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
