apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: core/linkerd-crds
    {{- if index .Values "linkerd-crds" "helm" }}
    helm:
      {{- toYaml index .Values "linkerd-crds" "helm" | nindent 6 }}
    {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
